name: Unit & Integration Tests
on:
    push:
    pull_request:

jobs:
    tests:
        name: 🧪 Tests
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4

            - name: 📦 Install
              uses: ./.github/common/install

            - name: 🔨 Build
              run: pnpm run build

            - name: 🧪 Test
              run: pnpm run test

